/**
 * Password hashing for the local-first credential store.
 *
 * PBKDF2-SHA256 via WebCrypto — no plaintext password is ever written to
 * IndexedDB or to the outbox. A temporary password generated by an admin is
 * shown once in the UI and then exists only as a hash.
 *
 * When a Supabase project is wired, Supabase Auth owns credentials instead and
 * these fields go unused; an admin-initiated reset there belongs in an Edge
 * Function holding the service_role key, which is the only place allowed to
 * set another user's password. See docs/09.
 */
const ITERATIONS = 150_000
const KEY_BITS = 256

const toHex = (buf: ArrayBuffer) =>
  Array.from(new Uint8Array(buf))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('')

const fromHex = (hex: string) => {
  const out = new Uint8Array(hex.length / 2)
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16)
  return out
}

export function randomSalt(): string {
  return toHex(crypto.getRandomValues(new Uint8Array(16)).buffer)
}

export async function hashPassword(password: string, salt: string): Promise<string> {
  const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, [
    'deriveBits',
  ])
  const bits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt: fromHex(salt), iterations: ITERATIONS, hash: 'SHA-256' },
    key,
    KEY_BITS,
  )
  return toHex(bits)
}

/** Constant-time-ish comparison; both operands are fixed-length hex digests. */
export function digestsEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false
  let diff = 0
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i)
  return diff === 0
}

export async function verifyPassword(password: string, salt: string, expected: string): Promise<boolean> {
  return digestsEqual(await hashPassword(password, salt), expected)
}

/* Ambiguous glyphs removed: an admin reads this over the phone. */
const ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'

export function generateTempPassword(groups = 3, size = 4): string {
  const bytes = crypto.getRandomValues(new Uint8Array(groups * size))
  const chars = Array.from(bytes, (b) => ALPHABET[b % ALPHABET.length])
  return Array.from({ length: groups }, (_, g) => chars.slice(g * size, g * size + size).join('')).join('-')
}

export function passwordProblem(password: string): string | null {
  if (password.length < 8) return 'Use at least 8 characters.'
  if (!/[a-zA-Z]/.test(password)) return 'Include at least one letter.'
  if (!/[0-9]/.test(password)) return 'Include at least one number.'
  return null
}
